# Generated by Django 3.1.7 on 2021-05-12 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GestionAsistencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaProfesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[{'1', 'Asistiré'}, {'Llegaré 15 minutos tarde', '2'}, {'3', 'No asistiré'}], max_length=24, null=True)),
                ('mensaje', models.TextField(blank=True, max_length=254, null=True)),
                ('dia', models.DateField(auto_now_add=True)),
                ('materia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestionAsistencia.clases')),
            ],
        ),
    ]
