# Generated by Django 3.1.7 on 2021-05-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AsistenciaProfesores', '0002_asistenciaprofesor_profesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistenciaprofesor',
            name='tipo',
            field=models.CharField(blank=True, choices=[{1, 'Asistiré'}, {2, 'Llegaré 15 minutos tarde'}, {3, 'No asistiré'}], max_length=24, null=True),
        ),
    ]
