# Generated by Django 3.1.7 on 2021-05-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AsistenciaProfesores', '0003_auto_20210513_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistenciaprofesor',
            name='tipo',
            field=models.CharField(blank=True, choices=[{'Sí sistiré', 'Asistiré'}, {'Llegaré 15 minutos tarde', 'Llegaré 15 minutos después'}, {'No asistiré', 'No iré'}], max_length=50, null=True),
        ),
    ]
