# Generated by Django 3.1.7 on 2021-05-12 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GestionAsistencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contenedor', models.CharField(blank=True, choices=[{1, 'Disponible'}, {2, 'No disponible'}], max_length=30, null=True)),
                ('Mensaje', models.CharField(blank=True, max_length=254, null=True)),
                ('Quejas', models.TextField(null=True)),
                ('Aula', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionAsistencia.ubicaciones')),
            ],
        ),
    ]
