# Generated by Django 3.1.7 on 2021-05-13 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionAsistencia', '0001_initial'),
        ('GestionAula', '0002_remove_notificaciones_quejas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aulacontenedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hora', models.DateTimeField(auto_now_add=True)),
                ('Aula', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionAsistencia.ubicaciones')),
            ],
        ),
        migrations.CreateModel(
            name='Aulaproductos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hora', models.DateTimeField(auto_now_add=True)),
                ('Aula', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionAsistencia.ubicaciones')),
            ],
        ),
        migrations.DeleteModel(
            name='Notificaciones',
        ),
    ]
