# Generated by Django 3.1.7 on 2021-05-12 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('capacidadActual', models.IntegerField()),
                ('capacidadMaxima', models.IntegerField()),
                ('estadoActual', models.BooleanField()),
                ('aforo', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Clases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('horario', models.TimeField()),
                ('profesor', models.CharField(max_length=50)),
                ('cupoDisponible', models.IntegerField()),
                ('ubicacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestionAsistencia.ubicaciones')),
            ],
        ),
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('expediente', models.IntegerField(blank=True, null=True)),
                ('materiaAsistir', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestionAsistencia.clases')),
            ],
        ),
    ]
