# Generated by Django 3.1.7 on 2021-05-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionQuejas', '0002_auto_20210512_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacionquejas',
            name='Queja',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
